let s = "Javascripts";
console.log(s);
console.log(s.toUpperCase());
console.log(s.toLowerCase());
console.log(s.slice(2, 6));
console.log(s.slice(6));
console.log(s.includes("s"));
console.log(s.includes("a"));
console.log(s.includes("a", 5));
console.log(s.indexOf("s"));
console.log(s.indexOf("s", 8));
console.log(s.indexOf("a", 7));
console.log(s.lastIndexOf("s"));
console.log(s.lastIndexOf("s", 8));
console.log(s.lastIndexOf("a", 7));
console.log(s.startsWith("s"));
console.log(s.startsWith("j"));
console.log(s.startsWith("J"));
console.log(s.startsWith("Jv"));
console.log(s.startsWith("Java"));
console.log(s.endsWith("j"));
console.log(s.endsWith("s"));
console.log(s.endsWith("J"));
console.log(s.endsWith("Jv"));
console.log(s.endsWith("ipts"));
console.log(s.substring(2, 7));
console.log(s.substring(7, 4));
console.log(s.substring(-4, -2));
console.log(s.substring(4, -2));
console.log(s.substring(-4, 6));
console.log(s.repeat(4));
console.log(s.replace("a", "x"));
console.log(s.replaceAll("a", "x"));
console.log(s.padStart(15, "a"));
console.log(s.padEnd(15, "a"));
console.log(s.charCodeAt(1));
console.log(String.fromCharCode(65));
console.log(s.split(""));
